name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Prepare
        run: npm ci

      - name: Run lint
        run: npm run lint
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      
      - name: Prepare
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build showcase
        run: npm run build:showcase

      - name: Build docs
        run: npm run docs

      - name: Run unit tests
        run: npm run test -- ngx-maplibre-gl --watch=false --no-progress --browsers=ChromeHeadless
        
      - name: Run e2e tests
        run: npm run e2e

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/videos
        if: ${{ failure() }}
